# Generated by Django 6.0.4 on 2026-05-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите аватар', null=True, upload_to='users/images/', verbose_name='Аватар'),
        ),
    ]
